// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usmnmvfxmjwzggrbhmle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbW5tdmZ4bWp3emdncmJobWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjE1MjIsImV4cCI6MjA3MTA5NzUyMn0.BGGO2ze_M543RGHVq5ab0iC9DrGaayP_iF4jn69SKhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});